/**
 * Brand-asset generator (Phase 2.04b, Tasks 2 + 3). Produces the raster brand marks and the
 * self-contained wordmark SVG from the ONE real Rubik display face already vendored for the OG cards
 * (src/app/og/rubik-latin-700.woff, SIL OFL) and the brand.md colour tokens. Run manually — NOT part
 * of the build — and the generated files are committed as static assets:
 *
 *   npx tsx scripts/generate-brand-assets.ts   (or: npm run assets:brand)
 *
 * WHY programmatic, not drawn by hand or by an image model: `D-0-6` bars AI-generated imagery. These
 * marks are pure typography — the brand's own name/initial set in the brand display font — so the
 * pipeline itself is the proof they are legitimate typographic marks, not generated pictures. next/og
 * (satori + resvg, already shipped with Next) rasterises them, so there is NO new dependency.
 *
 * Outputs:
 *   public/logo.svg        — the "Trajanov" wordmark, Rubik embedded as base64 so it is correct even
 *                            where Rubik is not installed (JSON-LD/general brand use).
 *   public/logo-512.png    — the wordmark on a solid ground square → Organization JSON-LD `logo`.
 *   public/icon-512.png    — the "T" monogram, 512, for the web manifest (installable icon).
 *   public/icon-192.png    — the "T" monogram, 192, for the web manifest.
 *   src/app/apple-icon.png — the "T" monogram, 180, App Router apple-touch-icon convention.
 *
 * Colours are brand.md §3 token VALUES mirrored as literals (satori/SVG cannot read a CSS custom
 * property — the same mirroring src/app/og and src/app/globals.css already do; D-2.04-2 / D-2.04b).
 */
import {ImageResponse} from 'next/og';
import type {ReactElement} from 'react';
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const GROUND = '#0F1210'; // --color-ground
const MUSTARD = '#E2A93C'; // --color-mustard

const woffPath = new URL('../src/app/og/rubik-latin-700.woff', import.meta.url);
const woff = readFileSync(woffPath);
const rubik = [{name: 'Rubik', data: woff, weight: 700 as const, style: 'normal' as const}];

// Resolve output paths relative to the repo root (this file lives in scripts/).
const root = new URL('../', import.meta.url);
const out = (rel: string) => fileURLToPath(new URL(rel, root));

// A React-element-like object tree (satori accepts these — no JSX/React import needed in a plain script).
type El = {type: string; props: Record<string, unknown>};
const el = (type: string, props: Record<string, unknown>): El => ({type, props});

/** The "Trajanov" wordmark centred on a solid ground square. */
function wordmark(size: number): El {
  return el('div', {
    style: {
      width: '100%',
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: GROUND,
      fontFamily: 'Rubik',
    },
    children: el('span', {
      style: {fontSize: Math.round(size * 0.164), fontWeight: 700, color: MUSTARD},
      children: 'Trajanov',
    }),
  });
}

/** The "T" monogram — the same geometry as src/app/icon.svg (proportions of a 512 canvas), so the
 *  favicon and the raster icons are the same mark. Drawn with divs so it needs no font. */
function monogram(size: number): El {
  const k = size / 512;
  const bar = (x: number, y: number, w: number, h: number): El =>
    el('div', {
      style: {
        position: 'absolute',
        left: x * k,
        top: y * k,
        width: w * k,
        height: h * k,
        borderRadius: 16 * k,
        backgroundColor: MUSTARD,
      },
    });
  return el('div', {
    style: {
      position: 'relative',
      width: '100%',
      height: '100%',
      display: 'flex',
      backgroundColor: GROUND,
    },
    children: [bar(116, 144, 280, 58), bar(227, 144, 58, 224)],
  });
}

async function png(element: El, size: number, dest: string): Promise<void> {
  const res = new ImageResponse(element as unknown as ReactElement, {
    width: size,
    height: size,
    fonts: rubik,
  });
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(dest, buf);
  console.log(`wrote ${dest} (${size}x${size}, ${buf.length} bytes)`);
}

/** The wordmark as a self-contained SVG: Rubik embedded as base64 so the mark is correct wherever the
 *  SVG is rendered, not only where Rubik is installed. Transparent ground so it composits anywhere. */
function writeLogoSvg(dest: string): void {
  const b64 = woff.toString('base64');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="560" height="180" viewBox="0 0 560 180" role="img" aria-label="Trajanov">
  <!-- Trajanov wordmark (Phase 2.04b Task 2). Rubik 700 embedded (SIL OFL) so it renders correctly
       everywhere; mustard #E2A93C is the brand.md §3 token value. Generated by scripts/generate-brand-assets.ts. -->
  <defs>
    <style>
      @font-face {
        font-family: 'Rubik';
        font-weight: 700;
        font-style: normal;
        src: url(data:font/woff;base64,${b64}) format('woff');
      }
    </style>
  </defs>
  <text x="280" y="122" text-anchor="middle" font-family="Rubik, ui-sans-serif, system-ui, sans-serif" font-weight="700" font-size="104" fill="#E2A93C">Trajanov</text>
</svg>
`;
  writeFileSync(dest, svg);
  console.log(`wrote ${dest} (wordmark SVG, embedded font)`);
}

async function main(): Promise<void> {
  writeLogoSvg(out('public/logo.svg'));
  await png(wordmark(512), 512, out('public/logo-512.png'));
  await png(monogram(512), 512, out('public/icon-512.png'));
  await png(monogram(192), 192, out('public/icon-192.png'));
  await png(monogram(180), 180, out('src/app/apple-icon.png'));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
